
version: 2.1
orbs:
    python: circleci/python@1.5.0


jobs:
    build-and-test:
    docker:
        - image: cimg/python:3.10.2
    steps:
        - checkout
        - run:
            name: Install Dependencies
            command: make install
        - run:
            name: Run Lint
            command: make lint

workflows:
    sample: 
        jobs:
            - build-and-test
